name: Github Release Build

on:
  workflow_dispatch: # To trigger specific workflow in a repository use workflow_dispatch, to trigger more than one workflow use repository_dispatch

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Build App Bundle
        run: ./gradlew bundleRelease

      - name: Upload App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release_aab
          path: app/build/outputs/bundle/release
          retention-days: 5

  deploy:
    name: Deploy Apk
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    steps:
      - name: Download Bundle
        uses: actions/download-artifact@v2
        with:
          name: release_aab
          path: app/build/outputs/bundle/release
