name: Github Build Workflow

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Build Type'
        required: false
        default: 'Debug Build'
jobs:
  build:
    name: Assemble Debug
    needs: checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Build Type Info
        run: echo "${{ github.event.inputs.type }} started"

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: ./gradlew assembleDebug


