name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ checks, setup ]
    steps:
      - name: Build
        run: ./gradlew assamble
