name: Github Build Workflow

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Build Command'
        required: false
        default: assembleDebug
jobs:
  build:
    name: Assemble Debug
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: ./gradlew ${{ github.event.inputs.command }}


