name: Github Build Workflow

on:
  workflow_dispatch: # To trigger specific workflow in a repository use workflow_dispatch, to trigger more than one workflow use repository_dispatch
    inputs:
      command:
        description: 'Build Command'
        required: false
        default: assembleDebug
      flavor:
        description: 'Flavor Type'
        required: false
        default: debug
jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: ./gradlew ${{ github.event.inputs.command }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/app-${{ github.event.inputs.flavor }}.apk
          retention-days: 5

  deploy:
    name: Deploy Apk
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/app-${{ github.event.inputs.flavor }}.apk

