name: Github Checks Workflow

on:
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    name: Lint and Unit Test Runs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: First Interaction Message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${ GITHUB_TOKEN }
          pr-message: "Thank you for your first contribution ${{ GITHUB_ACTOR }}"
          issue-message: "Thank you for your first issue ${{ GITHUB_ACTOR }}"

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Gradle Cache # 10GB cache limit
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }} # explicit key for restoring and saving the cache
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Detekt
        run: ./gradlew detekt

      #- name: Run Unit Tests
      # run: ./gradlew test

      # Scheduled trigger
      #
      #            ┌───────────── minute (0 - 59)
      #            │ ┌───────────── hour (0 - 23)
      #            │ │ ┌───────────── day of the month (1 - 31)
      #            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      #            │ │ │ │ ┌───────────── day of the week  (0 - 6 or SUN-SAT)
      #            │ │ │ │ │
      # schedule:
      #  - cron:  '* * * * *'
