name: Github Workflow
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  checks:
    name: Lint and Unit Test Runs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Gradle Cache # 10GB cache limit
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }} # explicit key for restoring and saving the cache
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Detekt
        run: ./gradlew detekt

      #- name: Run Unit Tests
      # run: ./gradlew test
  build:
    name: Assemble Debug
    needs: checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: ./gradlew assembleDebug
