name: Github Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  setup:
    name: Clone and JDK Setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
  checks:
    name: Lint and Unit Test Runs
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test
  build:
    name: Assable Builds
    needs: checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Build
        run: ./gradlew assamble
