name: Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: setup
    steps:
      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test
