name: Github Checks Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
env:
  # At the start of each run, Github automatically create a unique GITHUB_TOKEN secret to use in your workflow.
  # You can use the GITHUB_TOKEN to authenticate in a workflow run.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    name: Lint and Unit Test Runs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      USER_NAME: ${{ github.actor }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Gradle Cache # 10GB cache limit
        uses: actions/cache@v2
        env:
          OS_ENV: ${{ runner.os }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${OS_ENV}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} # explicit key for restoring and saving the cache
          restore-keys: ${OS_ENV}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Detekt
        run: ./gradlew detekt

      #- name: Run Unit Tests
      # run: ./gradlew test

      # Scheduled trigger
      #
      #            ┌───────────── minute (0 - 59)
      #            │ ┌───────────── hour (0 - 23)
      #            │ │ ┌───────────── day of the month (1 - 31)
      #            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      #            │ │ │ │ ┌───────────── day of the week  (0 - 6 or SUN-SAT)
      #            │ │ │ │ │
      # schedule:
      #  - cron:  '* * * * *'
