name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

env:
  # At the start of each run, Github automatically create a unique GITHUB_TOKEN secret to use in your workflow.
  # You can use the GITHUB_TOKEN to authenticate in a workflow run.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    name: Pull Request Lint and Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: First Interaction Message
        uses: actions/first-interaction@v1
        env:
          USER_NAME: ${{ github.actor }}
        with:
          repo-token: ${ GITHUB_TOKEN }
          pr-message: 'Thank you for your first contribution ${ USER_NAME }'

      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${ GITHUB_TOKEN }

      - name: Cache # 10GB cache limit
        uses: actions/cache@v2
        env:
          OS_NAME: ${{ runner.os }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${OS_ENV}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} # explicit key for restoring and saving the cache
          restore-keys: ${OS_ENV}-gradle-

      - name: Setup up JDK 11
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run detekt
        run: ./gradlew detekt
